server:
     port: 8888

spring:
     cloud:
         config:
            server:
                  git:
                    uri: https://github.com/DineshJayaprakash/HospitalManagementConfig.git



##https://github.com/DineshJayaprakash/MultiTenantConfig.git

##https://github.com/DineshJayaprakash/HospitalManagementConfig.git

##file:///D:/TrainingProjects/HospitalManagementConfig